FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build
WORKDIR /app

#copy csproj and restore as distinct layers
COPY *.sln .
COPY DockerTrial/*.csproj ./DockerTrial/
COPY DockerTrial/*.config ./DockerTrial/
RUN nuget restore

#copy everthing else
COPY DockerTrial/. ./DockerTrial/
WORKDIR /app/DockerTrial
RUN msbuild /p:Configuration=Release

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8 AS runtime
WORKDIR /inetpub/wwwroot
COPY --from=build /app/DockerTrial/. ./

EXPOSE 80
# The final instruction copies the site you published earlier into the container.
#COPY /DockerTrial/bin/Release/Publish/ /inetpub/wwwroot

